import Head from 'next/head'
import Header from '@/components/header'
import prisma from '@/components/prisma'
import showImages from '@/components/showImages'
import SearchBar from '@/components/searchbar'
import Image from 'next/image'


export default function Home({ photos }) {


  function getRandomInt(max) {
    return Math.floor(Math.random() * max);
  }
  const randomNumber = getRandomInt(photos.length)

  return (
    <div className='bg-custom-grey'>
      <Head>
        <title>My images</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

       <div className="relative h-96  mb-11 bg-cover bg-center ">
        <Image
         src={`/${photos[randomNumber]?.thumbnailUrl || '/appcontent/18048EB5-ACE3-499A-AFE5-D0CCB02513BC.JPG'}`}
         alt=""
         fill={true}
         className="object-cover w-full"
        />
        <SearchBar />
      </div>
    {showImages(photos)}
    </div>
  )
}

export async function getServerSideProps(context) {


  try {
    const photos = await prisma.photos.findMany()
    prisma.$disconnect()
    return {
      props: { photos }
    };
  } catch (error) {
    console.log(error)
  }
}